### ISSUE TITLE
Cannot import Client

### ISSUE THREAD

**Issue by alibeyram** [jaebradley/nba_data#86]
```>>> from nba_data import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/nba_data/__init__.py", line 1, in <module>
    from data.current_season_only import CurrentSeasonOnly
ModuleNotFoundError: No module named 'data'```

**Comment by jaebradley** [comment]
yikes, that's not good

**Comment by alibeyram** [comment]
Apparently, the package only works with python 2.
